### PR TITLE
Updated code file only

### PR DESCRIPTION
**Pull request by linuxgurugamer**
Here is the code update only.
Pretty simple, hope this helps.

### CODE REVIEW

**Comment by ec429** [comment]
Unfortunately, I've now realised something else.  `master` is not the active branch, in fact it's rather stale.  My currently active branch is `ksp1.1`, which I really ought to have merged by now and haven't.  (Besides 1.1 compatibility, it also changes most of the mod's game logic and UI, so basically everything.)
In theory the `ksp1.1` branch should still be fine on 1.1.3, but I'm having a bit of difficulty with my toolchain (since Mono decided to drop .NET 3.5 support, grr) so it might be a while before I can actually build it.

**Comment by linuxgurugamer** [comment]
ok, I could get the same fix into the 1.1 branch, and build it for you if you like.
I'm using VisualStudio (as you know), don't have any problems with .net 3.5

**Comment by ec429** [comment]
I've (_finally_) managed to get my toolchain working again.  And, AFAICT this fix is already on the ksp1.1 branch (since commit 11f752b) which should therefore already work fine with 1.1.3.  I'm just about to test it out, and assuming it works I'll cut a release.

**Comment by ec429** [comment]
Successfully merged, built, tested and cut release (0.2.2).

**Comment by linuxgurugamer** [comment]
Great!

**Pull request closed without merging**
